@startuml
title Switch validate FSM

[*] --> INIT
INIT --> WAIT_SCHEMA

WAIT_SCHEMA --> ERROR : error\ntimeout
WAIT_SCHEMA --> VALIDATE : complete
WAIT_SCHEMA : enter / schema-request

VALIDATE --> [*]
VALIDATE : enter / validate-flows
VALIDATE : enter / validate-meters

ERROR --> [*]

@enduml
